# Generated by Django 3.1.4 on 2020-12-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarn',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
