# Generated by Django 3.1.4 on 2020-12-05 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20201205_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='recipient',
            new_name='purpose',
        ),
    ]
