# Generated by Django 3.1.4 on 2020-12-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_auto_20201205_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
