# Generated by Django 3.1.4 on 2020-12-06 20:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_project_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pattern',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
