# Generated by Django 3.1.4 on 2020-12-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0012_auto_20201206_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarn',
            name='color_group',
            field=models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green'), ('blue', 'blue'), ('indigo', 'indigo'), ('violet', 'violet'), ('black', 'back'), ('white', 'white'), ('gray', 'gray'), ('brown', 'brown')], default='blue', max_length=50),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='care_instructions',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='grams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='hook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='yarn/images/'),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='yards',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
