# Generated by Django 3.1.4 on 2020-12-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0013_auto_20201206_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='color_group',
            field=models.CharField(choices=[('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green'), ('blue', 'blue'), ('purple', 'purple'), ('pink', 'pink'), ('black', 'black'), ('white', 'white'), ('gray', 'gray'), ('brown', 'brown')], default='blue', max_length=50),
        ),
    ]
