# Generated by Django 3.1.4 on 2020-12-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0015_auto_20201206_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='yarn/images/'),
        ),
    ]
