# Generated by Django 3.1.4 on 2020-12-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0016_auto_20201207_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='yarn',
            name='order_by',
            field=models.CharField(choices=[('', ''), ('color', 'color'), ('weight', 'weight'), ('brand', 'brand'), ('amount', 'amount')], default='', max_length=50),
        ),
    ]
