# Generated by Django 3.1.4 on 2020-12-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0017_yarn_order_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yarn',
            name='order_by',
        ),
    ]
