# Generated by Django 3.1.4 on 2020-12-09 01:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0018_remove_yarn_order_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIdeas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('descrition', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
