# Generated by Django 3.1.4 on 2020-12-09 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0019_projectideas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectideas',
            old_name='descrition',
            new_name='description',
        ),
    ]
